### ISSUE TITLE
Error with WebAssembly engine

### ISSUE THREAD

**Issue by scaljeri** [niklasf/stockfish.js#13]
When I try to use the web assembly version I get an error in the browser

![image](https://user-images.githubusercontent.com/1078741/66707436-ccbae100-ed40-11e9-9ad6-185303e35f26.png)

This is how I serve the `wasm` files with NestJs

    @Get('webworker-wasm.js')
    private getWebworkerWasmSfjs(req: Request, res: Response) {
        Logger.Info('Serving file ../../node_modules/stockfish.js/stockfish.wasm.js');

        fs.readFile('../../node_modules/stockfish.js/stockfish.wasm.js', 'utf8', (err: any, data: string) => {
            // Buffer.concat(data)
            if (err) {
                console.log(err);
            }

            res.setHeader('Access-Control-Allow-Origin', '*');
	        res.setHeader('Access-Control-Request-Method', '*');
	        res.setHeader('Access-Control-Allow-Methods', 'OPTIONS, GET');
            res.setHeader('Access-Control-Allow-Headers', '*');
            // res.setHeader('Content-Type', 'application/wasm');
            res.setHeader('Content-Type', 'application/javascript');

            // res.writeHead(200, {'Content-Type': 'application/wasm'});
            res.status(200).end(data);
        });
    }

    @Get('stockfish.wasm')
    private getWebworkerWasmSf(req: Request, res: Response) {
        Logger.Info('Serving file ../../node_modules/stockfish.js/stockfish.wasm');

        fs.readFile('../../node_modules/stockfish.js/stockfish.wasm', 'binary', (err: any, data: Buffer) => {
            // Buffer.concat(data)
            if (err) {
                console.log(err);
            }

            res.setHeader('Access-Control-Allow-Origin', '*');
	        res.setHeader('Access-Control-Request-Method', '*');
	        res.setHeader('Access-Control-Allow-Methods', 'OPTIONS, GET');
            res.setHeader('Access-Control-Allow-Headers', '*');
            res.setHeader('Content-Type', 'application/wasm');

            // res.writeHead(200, {'Content-Type': 'application/wasm'});
            res.status(200).end(data);
        });
    }

In my browser I execute it as follows

     engine = new Worker(`http://localhost:${this.port}/files/webworker-wasm.js`);
     engine.postMessage('uci');
     engine.postMessage('setoption name Move Overhead value 200');
     engine.postMessage('position fen rnbqkbnr/pppppppp/8/8/8/P7/1PPPPPPP/RNBQKBNR b KQkq - 0 1');
    engine.postMessage('go  wtime 59000 btime 60000');

Maybe I'm serving the files wrong or am I using wrong options. Any suggestions?

**Comment by niklasf** [comment]
I am not familiar with NestJs. Maybe use curl or something the verify that the files are served correctly?

**Comment by scaljeri** [comment]
I found the problem. It was indeed the way I was sending the wasm file. I still don't know why, but when I send the file using `res.sendFile('path-to-wasm')` it all works fine!
