### ISSUE TITLE
safari js error with unoptimized build

### ISSUE THREAD

**Issue by isaacl** [niklasf/stockfish.js#3]
| | optimize=no | optimize=yes
|------ | -------------- | ------------
Chrome 57 | ✔ | ✔ 
Firefox 49 | ✔ |✔
Safari 9.1.3 | :-(  |✔

The js error:
```
TypeError: Module['___cxa_is_pointer_type'] is not a function.
(In 'Module['___cxa_is_pointer_type'](throwntype)', 'Module['___cxa_is_pointer_type']' is undefined)
```

Built with OS X 10.11.6, LLVM 8.0.0, emscripten 1.37.1.  I was trying to debug the wonky elapsed clock in safari, but it's difficult to trace through without optimize=no.

**Comment by niklasf** [comment]
We no longer support Safari 9.
