### ISSUE TITLE
[Feature request] NPM package

### ISSUE THREAD

**Issue by futurliberta** [niklasf/stockfish.js#9]
Hello,

Is it possible to get a compiled version with a npm package ?

Thank you.

**Comment by niklasf** [comment]
Hi, in principle yes, but the way this is built it can only really run in a webworker. So I am not sure how to package it for npm in a way that's going to be useful.

**Comment by ryaninvents** [comment]
I think providing the web worker script as `index.js` would suffice:

- Consumers could download from unpkg.com or similar into the public asset directory of their project.
- A build step might copy the file from `node_modules/` into a public directory.
- If I recall correctly, `create-react-app` now scaffolds a service worker into a new project. This service worker could directly consume the published package.

I'd be glad to help set this up if need be.

**Comment by waltertamboer** [comment]
@niklasf It's useful to add it to the registry so people can add this package to their build process. For example, I now need to manually download a release and add it to my project. Would be much nicer if I can simply download the latest release via NPM/Yarn. Like @r24y also said, I have automated tasks (Grunt) that publish the files to the correct location

**Comment by niklasf** [comment]
My final concern with this is that I dislike committing the binaries to the repository. Right now the automated build uploads them as an attachment to the release tags. Suggestions?

**Comment by waltertamboer** [comment]
Yeah I see your point and I agree. I wonder if it's possible to let NPM download the assets you uploaded with a release? Maybe you can let Travis make the assets, upload them to your release and also add a `.npmignore` file which ignores all other files. No idea if it will work.

**Comment by waltertamboer** [comment]
https://hackernoon.com/how-to-publish-your-package-on-npm-7fc1f5aae600

**Comment by niklasf** [comment]
Now available as https://www.npmjs.com/package/stockfish.js, just the compiled files.
